### ISSUE TITLE
Tracking issue for V0.3

### ISSUE THREAD

**Issue by hellow554** [hellow554/logical-rs#2]
- [ ] Every function/member needs a (good) documentation
- [ ] Enable `#![forbid(missing_docs)]`
- [ ] Stabilize port / slot relation
